env:
  browser: true
  es2022: true
//typesciptを解釈させる
parser: '@typescript-eslint/parser'
  //ts.configの場所指定
  parserOptions:
    project: ./tsconfig.json
  plugins: [
    '@typescript-eslint' // ESLintのTypeScriptプラグインのルールを適用できる様にする（/eslint-pluginは省略可）
  ],
extends: [
  'eslint:recommended', // ESLintのJavaScriptルールセットを適用
  'plugin:@typescript-eslint/eslint-recommended', // eslint:recommendedに含まれるルールを型チェックでカバーできるものは無効化
  'plugin:@typescript-eslint/recommended', // 型チェックが不要なルールを適用
  'plugin:@typescript-eslint/recommended-requiring-type-checking', // 型チェックが必要なルールを適用
]