root: true
env:
  browser: true
  node: true
  es2021: true
#ts.configの場所指定
parser: 'vue-eslint-parser'
parserOptions:
  ecmaVersion: 13
  parser: '@typescript-eslint/parser'
  project: ./tsconfig.json
  extraFileExtensions:
    - '.vue'
#typesciptを解釈させる
plugins:
  #eslint-pluginは-省略可能
  - '@typescript-eslint' # ESLintのTypeScriptプラグインのルールを適用できる様にする（/eslint-pluginは省略可）
  - 'nuxt' #eslint-plugin-nuxtの指定
extends:
  #eslint-configは-省略可能
  # plugin:はeslint-plugin-などを記載する際に使える。これはpluginsに登録していなくても使える？
  - 'eslint:recommended' # ESLintのJavaScriptルールセットを適用
  # - 'plugin:vue/vue3-recommended'　vue3系は一旦外した
  - 'plugin:@typescript-eslint/eslint-recommended' # eslint:recommendedに含まれるルールを型チェックでカバーできるものは無効化
  - 'plugin:@typescript-eslint/recommended' # 型チェックが不要なルールを適用
  - 'plugin:@typescript-eslint/recommended-requiring-type-checking' # 型チェックが必要なルールを適用
  - '@nuxtjs/eslint-config-typescript'
  - 'plugin:nuxt/recommended'
  - 'prettier' # 一番最後にprettierを入れる
rules:
  object-curly-spacing: 0
  comma-spacing: 0
  indent:
    - 'error'
    - 4
  space-before-function-paren: 0
  semi: 0
  eol-last: 0
  arrow-parens: 0
  no-console: 0 # 開発中は抜きたい
  vue/html-indent:
    - 'error'
    - 4
  vue/html-self-closing:
    - 2
    - html:
        void:
          always
  vue/multi-word-component-names: 0